-- SUP-14085: Agent deletion (agentService.remove()) still returned 500 for
-- agents owning rows in decision/watchdog/project tables whose FKs to
-- agents / heartbeat_runs / agent_api_keys used ON DELETE NO ACTION (the
-- drizzle default), so the transaction rolled back and the agent was left
-- undeletable. This is the follow-up to 0220 (billing events), which chose
-- ON DELETE SET NULL for cost_events/finance_events.
--
-- Policies chosen per table:
--   CASCADE for agent-owned rows that have no meaning without the agent:
--     * issue_watchdogs.watchdog_agent_id      (the agent the watchdog acts as; no agent, no watchdog)
--     * decision_bundles / decisions origin_*  (generated by one run of one agent;
--                                                 they go away with that run)
--     * decision_archive_notification_outbox.origin_agent_id (never deliverable to a dead agent)
--     * company_skill_test_runs.agent_id       (was RESTRICT; an agent's skill test runs are owned by it)
--   ON DELETE SET NULL for nullable attribution FKs so history rows survive
--   with null agent/run references, and for the decision-table agent_api_keys
--   FKs that block the agent_api_keys delete step of remove().
--
-- Note: the decision tables carry *_check constraints tying an 'agent' actor
-- type to a non-null agent FK. agentService.remove() re-labels those rows as
-- type 'system' (and nulls the agent FK) inside the same transaction before
-- the FKs detach, so the check constraints stay intact.
--
-- Redo (SUP-14424): a plain ADD CONSTRAINT ... FOREIGN KEY acquires an
-- ACCESS EXCLUSIVE lock on the table and blocks all writers for the whole
-- validation scan, so replacing 30 FKs in one migration stalled fleet
-- writes during deploy. Each FK is now replaced online in two phases:
--   phase 1 (this file): ADD the new FK as a temporary constraint with
--      NOT VALID. This takes SHARE ROW EXCLUSIVE, which blocks concurrent
--      writers - but with no validation scan the lock is held only until
--      this migration's transaction commits, not for a full-table scan.
--   phase 2 (0223_agent_delete_fk_policies_validate.sql): VALIDATE the
--      temporary constraint, DROP the old constraint, and RENAME the
--      temporary constraint to the canonical name.
-- Redo 2 (SUP-14439): the VALIDATE/DROP/RENAME steps previously ran in this
-- same file, and the migration runner applies each file in ONE transaction,
-- so the write-blocking SHARE ROW EXCLUSIVE from phase 1 was held through
-- the entire validation scan. Validation now runs in its own committed
-- migration (0223), after this transaction releases its locks; there,
-- VALIDATE CONSTRAINT takes SHARE UPDATE EXCLUSIVE and the scan runs
-- concurrently with writers.
-- Temporary names are <canonical>_new. Three canonical names exceed
-- PostgreSQL's 63-byte identifier limit, where the truncated
-- <canonical>_new would collide with the truncated canonical name, so those
-- three use the deterministic short form <table>__new instead.
ALTER TABLE "issue_watchdogs" ADD CONSTRAINT "issue_watchdogs_watchdog_agent_id_agents_id_fk_new" FOREIGN KEY ("watchdog_agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_bundles" ADD CONSTRAINT "decision_bundles_origin_agent_id_agents_id_fk_new" FOREIGN KEY ("origin_agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_bundles" ADD CONSTRAINT "decision_bundles_origin_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("origin_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decisions" ADD CONSTRAINT "decisions_origin_agent_id_agents_id_fk_new" FOREIGN KEY ("origin_agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decisions" ADD CONSTRAINT "decisions_origin_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("origin_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_archive_notification_outbox" ADD CONSTRAINT "decision_archive_notification_outbox__new" FOREIGN KEY ("origin_agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "company_skill_test_runs" ADD CONSTRAINT "company_skill_test_runs_agent_id_agents_id_fk_new" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "approval_comments" ADD CONSTRAINT "approval_comments_author_agent_id_agents_id_fk_new" FOREIGN KEY ("author_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_requested_by_agent_id_agents_id_fk_new" FOREIGN KEY ("requested_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_created_by_agent_id_agents_id_fk_new" FOREIGN KEY ("created_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_owner_agent_id_agents_id_fk_new" FOREIGN KEY ("owner_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_lead_agent_id_agents_id_fk_new" FOREIGN KEY ("lead_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "routines" ADD CONSTRAINT "routines_assignee_agent_id_agents_id_fk_new" FOREIGN KEY ("assignee_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "join_requests" ADD CONSTRAINT "join_requests_created_agent_id_agents_id_fk_new" FOREIGN KEY ("created_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "issue_thread_interactions" ADD CONSTRAINT "issue_thread_interactions_created_by_agent_id_agents_id_fk_new" FOREIGN KEY ("created_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "issue_thread_interactions" ADD CONSTRAINT "issue_thread_interactions_resolved_by_agent_id_agents_id_fk_new" FOREIGN KEY ("resolved_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queues" ADD CONSTRAINT "decision_queues_created_by_agent_id_agents_id_fk_new" FOREIGN KEY ("created_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queue_items" ADD CONSTRAINT "decision_queue_items_added_by_agent_id_agents_id_fk_new" FOREIGN KEY ("added_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage" ADD CONSTRAINT "decision_triage_set_by_agent_id_agents_id_fk_new" FOREIGN KEY ("set_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage_events" ADD CONSTRAINT "decision_triage_events_actor_agent_id_agents_id_fk_new" FOREIGN KEY ("actor_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_retention" ADD CONSTRAINT "decision_retention_archived_by_agent_id_agents_id_fk_new" FOREIGN KEY ("archived_by_agent_id") REFERENCES "public"."agents"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queues" ADD CONSTRAINT "decision_queues_created_by_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("created_by_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queue_items" ADD CONSTRAINT "decision_queue_items_added_by_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("added_by_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage" ADD CONSTRAINT "decision_triage_set_by_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("set_by_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage_events" ADD CONSTRAINT "decision_triage_events_actor_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("actor_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_retention" ADD CONSTRAINT "decision_retention_archived_by_run_id_heartbeat_runs_id_fk_new" FOREIGN KEY ("archived_by_run_id") REFERENCES "public"."heartbeat_runs"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queues" ADD CONSTRAINT "decision_queues__new" FOREIGN KEY ("created_by_agent_api_key_id") REFERENCES "public"."agent_api_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_queue_items" ADD CONSTRAINT "decision_queue_items__new" FOREIGN KEY ("added_by_agent_api_key_id") REFERENCES "public"."agent_api_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage" ADD CONSTRAINT "decision_triage_set_by_agent_api_key_id_agent_api_keys_id_fk_new" FOREIGN KEY ("set_by_agent_api_key_id") REFERENCES "public"."agent_api_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
ALTER TABLE "decision_triage_events" ADD CONSTRAINT "decision_triage_events_agent_api_key_id_agent_api_keys_id_fk_new" FOREIGN KEY ("agent_api_key_id") REFERENCES "public"."agent_api_keys"("id") ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;--> statement-breakpoint
